import MonochromaticQuantumGraphs.N8D3.TropicalTerminalComponentB8.Class19.Character3
import MonochromaticQuantumGraphs.N8D3.TropicalTerminalComponentB8.Class19.Character4
import MonochromaticQuantumGraphs.N8D3.TropicalTerminalComponentB8.Class19.Character5
import MonochromaticQuantumGraphs.N8D3.TropicalTerminalComponentB8.Class19.Nested
