import MonochromaticQuantumGraphs.N8D3.TropicalBorderPolynomial8

/-!
# Reproducible axiom audit for the N=8, D=3 tropical border

This module prints the axiom dependencies of every theorem in the canonical
certificate, finite replay, normalized family, limit, closure, and polynomial
non-separation layers.
-/

#print axioms MonochromaticQuantumGraphs.N8D3.tropicalSupportSize8
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalEdgeSupported8_mkEdge_of_lt
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalEdgeValuation8_mkEdge_of_lt
#print axioms MonochromaticQuantumGraphs.N8D3.matchingEdges8_lt
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalTargetMatchingEdges8
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalTargetMatchingSupported8
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalTargetMatchingValuation8
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalTargetValuationSums8
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalTargetSelected8
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalStrictValuationGap8

#print axioms MonochromaticQuantumGraphs.N8D3.tropicalMonoColoring8_eq_monoColoring8
#print axioms MonochromaticQuantumGraphs.N8D3.matchingEdges8_left_eq_zero_iff
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalRawWeights8_matching_factor
#print axioms MonochromaticQuantumGraphs.N8D3.pmTerm8_tropicalRawWeights8
#print axioms MonochromaticQuantumGraphs.N8D3.pmSumN_tropicalRawWeights8
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalRawTermValue8_nonneg
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalRawTermValue8_target
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalRawMonoAmplitude8_pos
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalNormalizedWeights8_eq_zero_of_unsupported
#print axioms MonochromaticQuantumGraphs.N8D3.pmTerm8_tropicalNormalizedWeights8
#print axioms MonochromaticQuantumGraphs.N8D3.pmSumN_tropicalNormalizedWeights8_eq_raw
#print axioms MonochromaticQuantumGraphs.N8D3.pmSumN_tropicalNormalizedWeights8
#print axioms MonochromaticQuantumGraphs.N8D3.pmSumN_tropicalNormalizedWeights8_mono

#print axioms MonochromaticQuantumGraphs.N8D3.tropicalSelectedTarget8_eq_true_iff
#print axioms MonochromaticQuantumGraphs.N8D3.allEqual_iff_eq_tropicalMonoColoring8
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalSelectedTarget8_eq_false_of_not_allEqual
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalSelectedTarget8_mono_eq_false_of_ne
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalScaledTerm8_tendsto_zero
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalScaledTerm8_target
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalScaledAmplitude8_tendsto_zero
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalScaledAmplitude8_mono_tendsto_one
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalRawTermValue8_div_targetRate
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalRawAmplitude8_div_targetRate
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalNormalizedAmplitude8_eq_scaled
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalNormalizedAmplitude8_tendsto_zero
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalNormalizedAmplitude8_mono
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalNormalizedTensor8_coord_tendsto_zero
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalNormalizedTensor8_coord_mono_tendsto_one
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalNormalizedTensor8_tendsto_ghz
#print axioms MonochromaticQuantumGraphs.N8D3.tropicalNormalizedTensor8_mem_supportImage
#print axioms MonochromaticQuantumGraphs.N8D3.ghzTensor8_mem_closure_tropicalSupportTensorImage8

#print axioms MonochromaticQuantumGraphs.N8D3.polynomial_eq_zero_on_tropicalSupportTensorImage8_imp_eval_ghz_eq_zero
#print axioms MonochromaticQuantumGraphs.N8D3.polynomial_eq_zero_on_all_perfectMatchingTensor8_imp_eval_ghz_eq_zero
#print axioms MonochromaticQuantumGraphs.N8D3.no_polynomial_separates_perfectMatchingTensors8_from_ghz
