import MonochromaticQuantumGraphs.ColorRestriction
import MonochromaticQuantumGraphs.FactorStar
import MonochromaticQuantumGraphs.LocalContraction.PointwiseThree
import MonochromaticQuantumGraphs.N8D3.GeneratedData
import MonochromaticQuantumGraphs.N8D3.Basic
import MonochromaticQuantumGraphs.N8D3.TargetOrbitCertificates8
import MonochromaticQuantumGraphs.N8D3.Candidate129.ExactSupportTheorem
